
name: GitHub Actions To Build Verify and Release
on:
  release:
    types: [created]
jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean javafx:jlink
      - run: mkdir staging && cp target/*.zip staging
      - uses: actions/upload-artifact@v3
        with:
          name: Tuntikirjaus-package-with-jre
          path: staging