
name: Build Test and Package

on: workflow_dispatch

jobs:
  Build-Test-And-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java with maven cached
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests
        run: mvn clean test

      - name: Package JavaFx application with jlink
        run: mvn javafx:jlink

      - name: Create staging folder
        run: mkdir staging && cp target/*.zip staging

      - name: Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tuntikirjaus-package-with-jre
          path: staging
