name: GitHub Actions To Build Verify and Release
on:
  push:
    branches:
      - master
jobs:
  Build-Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify